# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowcost', '0004_flight_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='possible_way',
            field=models.ManyToManyField(related_name='_airport_possible_way_+', to='lowcost.Airport'),
        ),
    ]
